github = "https://github.com/pjvds/zsh-fzf-up"

changelog_path = "CHANGELOG.md"
pre_bump_hooks = []
post_bump_hooks = []
authors = [
    { signature = "Pieter Joost van de Sande", username = "pjvds" }
]

