[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "zsh-fzf-up"
owner = "pjvds"
authors = [
    { signature = "Pieter Joost van de Sande", username = "pjvds" }
]
